services:
  - type: web
    name: task-management-backend
    env: go
    region: singapore
    buildCommand: cd backend && go build -o app ./cmd/main.go
    startCommand: ./backend/app
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true
